# Generated by Django 2.0.2 on 2018-02-17 21:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('is_ready', models.BooleanField(default=False)),
                ('screenshot', models.TextField()),
                ('ref', models.UUIDField(db_index=True, default=uuid.uuid4)),
            ],
        ),
    ]
