# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('is_ready', models.BooleanField(default=False)),
                ('screenshot', models.TextField()),
                ('ref', models.UUIDField(db_index=True, default=uuid.uuid4)),
            ],
        ),
    ]
