# Generated by Django 2.0.2 on 2018-02-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='screenshot',
            field=models.TextField(default=''),
        ),
    ]
