# Generated by Django 2.0.2 on 2018-04-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20180226_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='screenshot',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
